{
 "title": "oura leaderboard",
 "tags": [ "kiosk" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "$name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "name" },
  {
   "title": "Readiness",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "bio.$name.readiness.score" }
   ]
  },
  {
   "title": "Sleep",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "bio.$name.sleep.score" }
   ]
  },
  {
   "title": "Activity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "bio.$name.activity.score" }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "bio.$name.hr.bpm" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 1 },
   "targets": [
    { "target": "bio.$name.hr.bpm" }
   ]
  }
 ]
}